-- CreateEnum
CREATE TYPE "IngredientCategory" AS ENUM ('produce', 'protein', 'dairy', 'grain', 'spice_condiment', 'pantry_staple', 'other');

-- CreateEnum
CREATE TYPE "DietTag" AS ENUM ('vegetarian', 'vegan', 'pescatarian', 'glutenFree', 'dairyFree', 'nutFree');

-- CreateEnum
CREATE TYPE "RecipeStatus" AS ENUM ('draft', 'enriching', 'published', 'needsReview', 'rejected', 'archived');

-- CreateEnum
CREATE TYPE "EnrichmentSource" AS ENUM ('seedImport', 'userSubmission', 'manualEdit');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "avatarUrl" TEXT,
    "googleId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Ingredient" (
    "id" TEXT NOT NULL,
    "canonicalName" TEXT NOT NULL,
    "category" "IngredientCategory" NOT NULL,
    "isAllergen" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Ingredient_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "IngredientAlias" (
    "id" TEXT NOT NULL,
    "ingredientId" TEXT NOT NULL,
    "aliasText" TEXT NOT NULL,
    "source" "EnrichmentSource" NOT NULL DEFAULT 'seedImport',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "IngredientAlias_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MoodTag" (
    "slug" TEXT NOT NULL,
    "displayName" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MoodTag_pkey" PRIMARY KEY ("slug")
);

-- CreateTable
CREATE TABLE "RecipeMoodTag" (
    "recipeId" TEXT NOT NULL,
    "moodTagSlug" TEXT NOT NULL,

    CONSTRAINT "RecipeMoodTag_pkey" PRIMARY KEY ("recipeId","moodTagSlug")
);

-- CreateTable
CREATE TABLE "Recipe" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "instructions" JSONB NOT NULL,
    "cuisine" TEXT,
    "prepTimeMinutes" INTEGER,
    "cookTimeMinutes" INTEGER,
    "baseServings" INTEGER NOT NULL DEFAULT 4,
    "imageUrl" TEXT,
    "sourceUrl" TEXT,
    "sourceAttribution" TEXT,
    "status" "RecipeStatus" NOT NULL DEFAULT 'draft',
    "dietTags" "DietTag"[],
    "dietTagsAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "submittedById" TEXT,
    "contentHash" TEXT NOT NULL,
    "embeddingModelVersion" TEXT,
    "mood_tags_text" TEXT,
    "ingredient_names_text" TEXT,
    "instructions_text" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Recipe_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RecipeIngredient" (
    "id" TEXT NOT NULL,
    "recipeId" TEXT NOT NULL,
    "ingredientId" TEXT NOT NULL,
    "rawText" TEXT NOT NULL,
    "quantity" DOUBLE PRECISION,
    "unit" TEXT,
    "isOptional" BOOLEAN NOT NULL DEFAULT false,
    "scalesLinearly" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL,

    CONSTRAINT "RecipeIngredient_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PantryItem" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "ingredientId" TEXT NOT NULL,
    "quantity" DOUBLE PRECISION,
    "unit" TEXT,
    "expiresAt" TIMESTAMP(3),
    "addedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PantryItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SavedRecipe" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "recipeId" TEXT NOT NULL,
    "note" TEXT,
    "savedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SavedRecipe_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CookedLog" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "recipeId" TEXT NOT NULL,
    "rating" INTEGER,
    "note" TEXT,
    "cookedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CookedLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SubstitutionEdge" (
    "id" TEXT NOT NULL,
    "fromIngredientId" TEXT NOT NULL,
    "toIngredientId" TEXT NOT NULL,
    "context" TEXT,
    "confidence" DOUBLE PRECISION NOT NULL DEFAULT 0.7,
    "source" "EnrichmentSource" NOT NULL DEFAULT 'seedImport',

    CONSTRAINT "SubstitutionEdge_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SearchEvent" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "rawQuery" TEXT NOT NULL,
    "extractedIngredientIds" TEXT[],
    "extractedFilters" JSONB,
    "vibeAmount" DOUBLE PRECISION NOT NULL,
    "usedLlmExtraction" BOOLEAN NOT NULL DEFAULT false,
    "resultRecipeIds" TEXT[],
    "clickedRecipeId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SearchEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "User_googleId_key" ON "User"("googleId");

-- CreateIndex
CREATE UNIQUE INDEX "Ingredient_canonicalName_key" ON "Ingredient"("canonicalName");

-- CreateIndex
CREATE UNIQUE INDEX "IngredientAlias_aliasText_key" ON "IngredientAlias"("aliasText");

-- CreateIndex
CREATE INDEX "IngredientAlias_ingredientId_idx" ON "IngredientAlias"("ingredientId");

-- CreateIndex
CREATE INDEX "Recipe_status_idx" ON "Recipe"("status");

-- CreateIndex
CREATE INDEX "RecipeIngredient_recipeId_idx" ON "RecipeIngredient"("recipeId");

-- CreateIndex
CREATE INDEX "RecipeIngredient_ingredientId_idx" ON "RecipeIngredient"("ingredientId");

-- CreateIndex
CREATE INDEX "PantryItem_userId_idx" ON "PantryItem"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "PantryItem_userId_ingredientId_key" ON "PantryItem"("userId", "ingredientId");

-- CreateIndex
CREATE UNIQUE INDEX "SavedRecipe_userId_recipeId_key" ON "SavedRecipe"("userId", "recipeId");

-- CreateIndex
CREATE INDEX "CookedLog_userId_idx" ON "CookedLog"("userId");

-- CreateIndex
CREATE INDEX "CookedLog_recipeId_idx" ON "CookedLog"("recipeId");

-- CreateIndex
CREATE UNIQUE INDEX "SubstitutionEdge_fromIngredientId_toIngredientId_context_key" ON "SubstitutionEdge"("fromIngredientId", "toIngredientId", "context");

-- CreateIndex
CREATE INDEX "SearchEvent_createdAt_idx" ON "SearchEvent"("createdAt");

-- AddForeignKey
ALTER TABLE "IngredientAlias" ADD CONSTRAINT "IngredientAlias_ingredientId_fkey" FOREIGN KEY ("ingredientId") REFERENCES "Ingredient"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecipeMoodTag" ADD CONSTRAINT "RecipeMoodTag_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "Recipe"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecipeMoodTag" ADD CONSTRAINT "RecipeMoodTag_moodTagSlug_fkey" FOREIGN KEY ("moodTagSlug") REFERENCES "MoodTag"("slug") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Recipe" ADD CONSTRAINT "Recipe_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecipeIngredient" ADD CONSTRAINT "RecipeIngredient_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "Recipe"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RecipeIngredient" ADD CONSTRAINT "RecipeIngredient_ingredientId_fkey" FOREIGN KEY ("ingredientId") REFERENCES "Ingredient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PantryItem" ADD CONSTRAINT "PantryItem_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PantryItem" ADD CONSTRAINT "PantryItem_ingredientId_fkey" FOREIGN KEY ("ingredientId") REFERENCES "Ingredient"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SavedRecipe" ADD CONSTRAINT "SavedRecipe_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SavedRecipe" ADD CONSTRAINT "SavedRecipe_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "Recipe"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CookedLog" ADD CONSTRAINT "CookedLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CookedLog" ADD CONSTRAINT "CookedLog_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "Recipe"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SubstitutionEdge" ADD CONSTRAINT "SubstitutionEdge_fromIngredientId_fkey" FOREIGN KEY ("fromIngredientId") REFERENCES "Ingredient"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SubstitutionEdge" ADD CONSTRAINT "SubstitutionEdge_toIngredientId_fkey" FOREIGN KEY ("toIngredientId") REFERENCES "Ingredient"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SearchEvent" ADD CONSTRAINT "SearchEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Extensions (must exist before the vector type / gin_trgm_ops operator class below)
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Recipe.embedding: pgvector column + HNSW index (SRS §8.3 / §8.2)
-- Not expressible in schema.prisma; modeled there as a comment only.
ALTER TABLE "Recipe" ADD COLUMN "embedding" vector(1536);
CREATE INDEX recipe_embedding_hnsw_idx ON "Recipe"
  USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);
-- m / ef_construction are reasonable starting points (SRS changelog item 10), not tuned;
-- revisit once the corpus is large enough to measure recall-vs-latency on real query patterns.

-- Recipe.search_vector: generated tsvector column + GIN index (SRS §8.3 / §8.2)
-- Prisma has no concept of a computed column; not expressible in schema.prisma at all.
ALTER TABLE "Recipe" ADD COLUMN search_vector tsvector
  GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(mood_tags_text, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(ingredient_names_text, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(description, '')), 'C') ||
    setweight(to_tsvector('english', coalesce(instructions_text, '')), 'D')
  ) STORED;
CREATE INDEX recipe_search_vector_idx ON "Recipe" USING gin (search_vector);

-- IngredientAlias.aliasText trigram index (SRS §8.3 / §8.2)
-- Prisma can declare a plain index but not one with a non-default operator class.
CREATE INDEX ingredient_alias_trgm_idx ON "IngredientAlias"
  USING gin ("aliasText" gin_trgm_ops);